from enum import Enum

class ErrorCodeEnum(Enum):
    """Request Form Error Codes."""

    GENERIC = "GENERIC_ERROR"

    # Brand
    BRAND_STORE_EXISTS = "BRAND_STORE_EXISTS_ERROR"
    # SupercardPrefix
    SUPERCARD_PREFIX_SUPERCARD_BATCH_EXISTS = "SUPERCARD_PREFIX_SUPERCARD_BATCH_EXISTS_ERROR"

    PROCESSING_ERROR = "GENERIC_ERROR"
    
    # NotificationOptOut
    NOTIFICATION_OPTOUT_MOBILE_EMAIL_EXISTS = "NOTIFICATION_OPTOUT_MOBILE_EMAIL_EXISTS_ERROR"