"""create tables

Revision ID: aa08ef8f826a
Revises: 
Create Date: 2026-03-10 23:47:47.356121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa08ef8f826a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('guest_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=250), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified_by', sa.String(length=250), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('modified_reason', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('guest_id')
    )
    op.create_index('idx_guest_email', 'guest', ['email'], unique=False)
    op.create_index('idx_guest_is_deleted', 'guest', ['is_deleted'], unique=False)
    op.create_table('todo',
    sa.Column('todo_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=250), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified_by', sa.String(length=250), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('modified_reason', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('todo_id')
    )
    op.create_index('idx_todo_is_deleted', 'todo', ['is_deleted'], unique=False)
    op.create_index('idx_todo_priority', 'todo', ['priority'], unique=False)
    op.create_index('idx_todo_status', 'todo', ['status'], unique=False)
    op.create_table('todo_guest',
    sa.Column('todo_id', sa.BigInteger(), nullable=False),
    sa.Column('guest_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.guest_id'], ),
    sa.ForeignKeyConstraint(['todo_id'], ['todo.todo_id'], ),
    sa.PrimaryKeyConstraint('todo_id', 'guest_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_guest')
    op.drop_index('idx_todo_status', table_name='todo')
    op.drop_index('idx_todo_priority', table_name='todo')
    op.drop_index('idx_todo_is_deleted', table_name='todo')
    op.drop_table('todo')
    op.drop_index('idx_guest_is_deleted', table_name='guest')
    op.drop_index('idx_guest_email', table_name='guest')
    op.drop_table('guest')
    # ### end Alembic commands ###
